export const contacts = [
  {
    name: 'Sven Sven',
    location: 'Curnovec, SI',
    email: 'sven@brembo.com',
    phone: '+1 12314123',
    additional: 'Here',
    id: '1',
  },
  {
    name: 'Sven Sven',
    location: 'Curnovec, SI',
    email: 'sven@brembo.com',
    phone: '+1 12314123',
    additional: 'Here',
    id: '2',
  },
  {
    name: 'Sven Sven',
    location: 'Curnovec, SI',
    email: 'sven@brembo.com',
    phone: '+1 12314123',
    additional: 'Here',
    id: '3',
  },
  {
    name: 'Sven Sven',
    location: 'Curnovec, SI',
    email: 'sven@brembo.com',
    phone: '+1 12314123',
    additional: 'Here',
    id: '4',
  },
  {
    name: 'Sven Sven',
    location: 'Curnovec, SI',
    email: 'sven@brembo.com',
    phone: '+1 12314123',
    additional: 'Here',
    id: '5',
  },
  {
    name: 'Sven Sven',
    location: 'Curnovec, SI',
    email: 'sven@brembo.com',
    phone: '+1 12314123',
    additional: 'Here',
    id: '6',
  },
  {
    name: 'Sven Sven',
    location: 'Curnovec, SI',
    email: 'sven@brembo.com',
    phone: '+1 12314123',
    additional: 'Here',
    id: '7',
  },
  {
    name: 'Sven Sven',
    location: 'Curnovec, SI',
    email: 'sven@brembo.com',
    phone: '+1 12314123',
    additional: 'Here',
    id: '8',
  },
  {
    name: 'Sven Sven',
    location: 'Curnovec, SI',
    email: 'sven@brembo.com',
    phone: '+1 12314123',
    additional: 'Here',
    id: '9',
  },
  {
    name: 'Sven Sven',
    location: 'Curnovec, SI',
    email: 'sven@brembo.com',
    phone: '+1 12314123',
    additional: 'Here',
    id: '10',
  },
  {
    name: 'Sven Sven',
    location: 'Curnovec, SI',
    email: 'sven@brembo.com',
    phone: '+1 12314123',
    additional: 'Here',
    id: '11',
  },
  {
    name: 'Sven Sven',
    location: 'Curnovec, SI',
    email: 'sven@brembo.com',
    phone: '+1 12314123',
    additional: 'Here',
    id: '12',
  },
]
